# Generated by Django 4.1.3 on 2022-12-03 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("watchlist_app", "0005_review_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reviewed_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
